### GET all cakes
GET http://localhost:5000/api/cakes

### GET a cake
GET http://localhost:5000/api/cakes/617d4d8f2352f138f62cdb60

### Login a user
POST http://localhost:5000/api/users/login 
Content-type: application/json

{
        "email": "test@test.fr",
        "password": "12345",
        "pseudo": "katascakes"
}
